# Utilizando o GitHub Actions para fazer o deploy automaticamente no Glitch

name: CI

# Controls when the workflow will run
on:
  # Triggers que ativaram o actions
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Workflow onde uma ou mais tasks poderão ser executadas
jobs:
  # Nome da pipeline
  Glitch-SYNC:
    # Onde o processo será executado
    runs-on: ubuntu-latest

    # Sequencia de tarefas a serem executadas
    steps:
      - uses: kanadgupta/glitch-sync@v1.1

      # Runs a single command using the runners shell
      - name: Glitch-Deploy
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
