# Utilizando o GitHub Actions para fazer o deploy automaticamente no Glitch

name: CI

# Controls when the workflow will run
on:
  # Triggers que ativaram o actions
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Workflow onde uma ou mais tasks poderão ser executadas
jobs:
  # Nome da pipeline
  Glitch-SYNC:
    # Onde o processo será executado
    runs-on: ubuntu-latest
    
    # Sequencia de tarefas a serem executadas
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.head_ref }}
          
      - name: Configurar JDK
        uses: actions/setup-java@v2
        with: 
          java-version: 8
          distribution: "adopt"
          cache: gradle
          
      - name: build
        run: ./gradlew buildAllProducts
        
      - name: Montar Pastas
        run: rm -rf webappbuild && mkdir webappbuild && mv build/output webappbuild
        
      - name: Inicializador do Glitch
        run: |
          rand=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 11) && json='{"name":"NikaTasks","description":"Um projeto de ToDoList","version":"1.0.0","scripts":{"start":"if [ -e ./output ]; then rm -rf build && mkdir build && mv output build; fi && bash build/output/NikaTasks/start.sh"},"repository":{"type":"git","url":"https://github.com/DavidAS-BR/NikaTasks.git"},"keywords":[],"author":"GrupoProjeto","license":"MIT","keywords":["$rand"],"bugs":{"url":"https://github.com/DavidAS-BR/NikaTasks/issues"},"homepage":"https://roomy-antique-gray.glitch.me"}' && echo "$json" >> webappbuild/package.json
      - name: Commit report
        run: |
          git config --global user.name 'DavidAS-BR'
          git config --global user.email 'DavidAS-BR@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add --force -A
          git commit -am "Teste [ci-skip]"
          git push --force
 
      - name: Glitch-Deploy
        uses: kanadgupta/glitch-sync@v1.1
        with:
          project-id: '${{ secrets.projectId }}'
          auth-token: '${{ secrets.authToken }}'
          path: 'webappbuild' # optional
