# Utilizando o GitHub Actions para fazer o deploy automaticamente no Glitch

name: CI

# Controls when the workflow will run
on:
  # Triggers que ativaram o actions
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Workflow onde uma ou mais tasks poderão ser executadas
jobs:
  # Nome da pipeline
  Glitch-SYNC:
    # Onde o processo será executado
    runs-on: ubuntu-latest
    
    # Sequencia de tarefas a serem executadas
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Configurar JDK
        uses: actions/setup-java@v2
        with: 
          java-version: 8
          distribution: "adopt"
          cache: gradle
          
      - name: build
        run: ./gradlew buildAllProducts
        
      - name: Montar Pastas
        run: mkdir webappbuild && mv build webappbuild && echo "build/**" >> .clear-target-files
        
      - name: Inicializador do Glitch
        run: v1=$(tr -dc 0-9 </dev/urandom | head -c 1) && v2=$(tr -dc 0-9 </dev/urandom | head -c 1) && v3=$(tr -dc 0-9 </dev/urandom | head -c 1)

	run: json='{"name":"NikaTasks","description":"Um projeto de ToDoList","version":"1.0.0","scripts":{"start":"bash output/NikaTasks/start.sh"},"repository":{"type":"git","url":"https://github.com/DavidAS-BR/NikaTasks.git"},"keywords":[],"author":"GrupoProjeto","license":"MIT","bugs":{"url":"https://github.com/DavidAS-BR/NikaTasks/issues"},"homepage":"https://roomy-antique-gray.glitch.me"}'
         
	run: echo "$json" >> webappbuild/build/package.json
          
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main # The branch name where you want to push the assets
          FOLDER: webappbuild # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg} [ci-skip]" # The commit message
          CLEAR_GLOBS_FILE: ".clear-target-files"
          
      - name: Glitch-Deploy
        uses: kanadgupta/glitch-sync@v1.1
        with:
          project-id: '${{ secrets.projectId }}'
          auth-token: '${{ secrets.authToken }}'
          path: 'build' # optional